apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-aks-deployment

spec:
  selector:
    matchLabels:
      app: sample-angular-app
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-angular-app
    spec:
      containers:
      - name: angular-aks-sample-app
        image: amit4498/aks-angular-app
        ports:
        - containerPort: 8080