apiVersion: v1
kind: Service
metadata:
  name: angular-aks-service

spec:
  selector:
    app: sample-angular-app
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 443
      name: https