name: Check CodeQL

on:
  workflow_dispatch:

jobs:
  code-ql:
    runs-on: [ubuntu-latest]
    steps:
    - uses: ./.github/actions/sonar/
      with:
        app-directory: "."

       
