name: Check CodeQL

on:
  workflow_dispatch:

jobs:
  code-ql:
    uses: ./.github/actions/sonar/action.yaml@develop
      with:
        app-directory: "."
      secrets: inherit

       
