name: Check CodeQL

on:
  workflow_dispatch:

jobs:
  code-ql:
    runs-on: [ubuntu-latest]
    steps:
    -  uses: actions/checkout@v3
    -  uses: ./.github/actions/sonar/
       with:
         app-directory: "."
       shell: bash
       
