name: Build by Reusable
on:
  workflow_dispatch:

jobs:
  Node-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running reusable build action
        uses: ./github/actions/
        with:
          app-dir: "."

      - name: Running list for build contents
        run: |
          cd dist
          ls -lart
